module SkelExp where

-- Haskell module generated by the BNF converter

import AbsExp
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transExp :: Exp -> Result
transExp x = case x of
  EAdd exp1 exp2 -> failure x
  EInt integer -> failure x

